### PR TITLE
feat: add 'aside' as a shortcode

### LINKED ISSUE #4: <aside> Shortcode
See https://defcon.social/@benjaminhollon@fosstodon.org/109904976484255587

### PR DESCRIPTION
**Pull request by rluetzner**
The README has been updated to show a code example of both, including an exemplary screenshot.

Since Hugo 0.55, we have to use `markdownify` in shortcodes that contain HTML elements. At least we have to, if we want to render markdown code inside the HTML element.

This fixes #4.

### CODE REVIEW

**Comment by rluetzner** [comment]
That was surprisingly easy. I found [this discussion](https://discourse.gohugo.io/t/misunderstanding-of-shortcode-syntax-in-0-55/18538/6) on Hugo's discourse.

I've been trying to figure out a way to do this for multiple months now. Real happy I found this. 🥳

**Comment by rluetzner** [comment]
I don't know if you want binary files in your Git repo, @cjtheham . I can remove the image if you want.

**Comment by rluetzner** [comment]
Aaaaah!!! Wait! I forgot something. We need to wrap the `{{ .Content }}` inside an `<article>` element. I'll be right back.

**Comment by cjtheham** [comment]
No worries @rluetzner :joy: I'll leave it open till you're ready to merge with `<article>` in.

My one request RE: images - if you could throw it in the `docs/` folder that's fine by me, give them an easy way to delete it if it gets too large :joy:

**Comment by cjtheham** [comment]
BTW - is there a typo in the shortcodes folder name? `shortcodees`?

**Comment by rluetzner** [comment]
Done, done and done. Thanks for telling me about `shortcodees`. I didn't notice that. 😅

**Comment by cjtheham** [comment]
No problem! :)

Once I'm done with classes and work for the night I'll give it a quick test in the demo repo with the new updates and try and get this merged!

**Comment by rluetzner** [comment]
No worries. It's nighttime here in Germany already, so I'm done for the day. 😅 

I've tested the changes on my own website and already uploaded them. It looks way nicer with the aside element.

I'll eventually remove the duplicate code from my website when a new version of the theme is released.

Have a good day. 🙂

**Comment by benjaminbhollon** [comment]
> Aaaaah!!! Wait! I forgot something. We need to wrap the `{{ .Content }}` inside an `<article>` element. I'll be right back.

Ha, yes! An easy one to forget. XD

I should probably add something about that to the wiki; perhaps a page on blog post layout and related features, since that's a major usecase that's emerged for readable.css.

**Comment by cjtheham** [comment]
Aside is now also tested and functioning. I'll go ahead and close and merge this, and I can take a look into testing and working on #1 with the new updates.

**Comment by benjaminbhollon** [comment]
One note on the documentation:

> readable.css prefers the `<aside>` HTML element over blockquotes. This theme supports both.

Should probably be clarified that readable.css does indeed prefer blockquotes if you're actually quoting something. But if you're just wanting to put in a side note about the content, `<aside>` is better.

**Comment by rluetzner** [comment]
Thanks @benjaminbhollon . I'll update the README. Sorry, but I only now actually read through your documentation of readable.css, so that one's on me.

**Comment by benjaminbhollon** [comment]
> Thanks @benjaminbhollon . I'll update the README. Sorry, but I only now actually read through your documentation of readable.css, so that one's on me.

Ha, no problem. Classless CSS frameworks don't tend to have you expecting to need documentation, and for the most part you don't in readable.css. Its goal is basically to take your websites from good to great. ;)

**Pull request merged**
