### PR TITLE
CI: Add GitHub workflow to check for readable.css updates

### PR DESCRIPTION
**Pull request by rluetzner**
This adds a workflow and accompanying script to update readable.css. The script gets the latest tag version from the readable.css repository on codeberg.org and compares it to the currently used version. If the versions don't match up, we download readable.css and readable.min.css from Codeberg and update layouts/partials/head.html.

I initially didn't bother to check the current version, because ultimately we only do 3 requests against Codeberg every time the workflow executes. However, I'm expecting this workflow to run once a day currently. If someone were to increase the frequency significantly, this might become problematic for Codeberg. It's easy enough to optimize, so we should do it.

The workflow uses 'peter-evans/create-pull-request@v5', an action that allows us to create GitHub pull requests on the repo.

The action seems really thought through to me. I checked that an existing pull request is not duplicated. In case the 'main' branch changes in between, it will simply force push changes to the existing pull request. This also means that we won't get flooded with pull requests for the same version update.

If no changes are found, then the action will not open up a pull request at all.

The repository's settings need to be adjusted to allow workflows to create pull requests. This can be done in GitHub, by opening up the repository's 'Settings', clicking 'Actions' and 'General' and updating 'Workflow permissions' to allow 'Read and write permissions' and 'Allow GitHub Actions to create and approve pull requests'.

Other than that, there's nothing to do to enable this workflow. Once this commit is merged, the workflow will start it's scheduled execution.

The only thing I couldn't seem to get working is a notification for the newly created pull request. I'm not sure if I was simply unable to get it to work with a fork, or what's the reason behind this. I would have expected an email at least. However, I think this can be optimized in a future commit.

### CODE REVIEW

**Comment by rluetzner** [comment]
Sorry for the long text, but I wanted to be thorough.

Here's an example pull request that this created on my fork: https://github.com/rluetzner/hugo-theme-readable/pull/4.

In case you're wondering why this only updates the version in the `<link>` element -- it's because that is all I reverted to test this. I've previously verified that wether the *.css files were deleted or reverted, running the script downloaded the exact same versions as before. This can be easily verified by not having a `git diff` afterwards. :slightly_smiling_face: 

I've tested this a bunch on my local machine and then again with multiple scheduled runs with GitHub Actions. I realized that I could just have added a manual trigger to this workflow to speed up testing, but I actually kinda liked this rhythm of iteration. :sweat_smile:

**Comment by cjtheham** [comment]
This is awesome - thank you! I'm not feeling 100% today, and I've got work all day tomorrow, but when I can I plan on sitting down and knocking out a bunch of open-source work including your two open PRs here. Thanks for the contributions :)

**Comment by benjaminbhollon** [comment]
*bumps readable.css version just to see this thing at work*

**Review by benjaminbhollon — APPROVED** [review]
Looking good to me! (Though I haven't actually tested it.)

One slight note that doesn't actually need fixing, but where you link to the changelog, that isn't necessarily the full changelog. It'll generally contain all the notable changes for the release, but a full changelog is now in the repo as of v1.1.0: https://codeberg.org/Freedom-to-Write/readable.css/src/branch/main/CHANGELOG.md

Again no need to fix that if you don't feel like it; there shouldn't be a practical difference.

**Comment by rluetzner** [comment]
> I'm not feeling 100% today

I hope you feel better soon. 🙂 Take all the time and rest you need.

----

This is actually pretty easy to test (on Linux/a Linux container). At least the script part is.

1. You can **delete the .css files and decrease the version in head.html manually**. Simply reverting the last "update version" commit will not work as easily, because that's where `readable.css` was changed to `readable.min.css` in 'head.html'.
2. Check `git status`. It will tell you the files have changed.
3. Run the script `.github/scripts/update-readable-css.sh`.
4. Check `git status` again. There should be no more changes.

**Comment by rluetzner** [comment]
Oh and thanks for linking the Changelog file, @benjaminbhollon. I'll replace the link as soon as I get to a PC. 😅

**Comment by rluetzner** [comment]
Oops. Didn't mean to close this. I merely pushed an update and accidentally deleted my commit. 😅

**Comment by rluetzner** [comment]
Sorry for the confusion. All I did was update the URL for the changelog. 🙂

**Comment by cjtheham** [comment]
Finally getting around to reviewing some code today - sorry for the delay guys! This looks good, will go ahead and merge. Thanks for the hard work @rluetzner!

Note for the future: multiple commits in a PR is fine, to avoid accidental closures like that 😂. I've got it set to squash and merge for every PR.

@benjaminbhollon You can go ahead and add some new stuff to watch the script in action :)

**Comment by benjaminbhollon** [comment]
Haha, you've got me considering it. :)

**Pull request merged**
